### ISSUE TITLE
Make lock-api optional

### ISSUE THREAD

**Issue by notgull** [sunfishcode/rustix-futex-sync#10]
It might be nice for users who just want the raw mutex impl without bringing in the `lock-api` dependency.

**Comment by sunfishcode** [comment]
Sounds straightforward. I've now posted https://github.com/sunfishcode/rustix-futex-sync/pull/11 as a patch to implement this.

**Comment by sunfishcode** [comment]
This is now released in rustix-futex-sync 0.2.2.
